#! /bin/sh

if [ "$1" = "--version" ]
then
cat << EOF
ccs-editpolicy 1.6.7-pre

Copyright (C) 2005-2009 NTT DATA CORPORATION.

This program is free software; you may redistribute it under the terms of
the GNU General Public License. This program has absolutely no warranty.
EOF
elif [ "$1" = "--help" ]
then
cat << EOF
Usage: ccs-editpolicy [{s|e|d|p|m|q}] [readonly] [refresh=interval]

This program edits TOMOYO Linux's policy currently loaded in the kernel.

 s     Set initial screen to system policy editor.

 e     Set initial screen to exception policy editor.

 d     Set initial screen to domain policy editor. This is default.

 p     Set initial screen to profile editor.

 m     Set initial screen to manager editor.

 q     Set initial screen to memory quota editor.

 readonly             Browse mode. No editing is allowed.

 refresh=interval     Reload automatically for every sec seconds.

Examples:

# ccs-editpolicy
 Start policy editor with domain policy editor screen.

Usage with images are available at http://tomoyo.sourceforge.jp/en/1.6.x/tool-editpolicy.html

EOF
else
cat << EOF | help2man -i - -N -s 8 -n "Edit TOMOYO Linux's policy" $0 | gzip -9 > man8/ccs-editpolicy.8.gz
[SEE ALSO]

 ccs-loadpolicy (8)

[NOTES]

 This is a symbolic link to /usr/lib/ccs/editpolicy .

 You need to register either path to this program ( /usr/lib/ccs/editpolicy ) or a domain for this program in /proc/ccs/manager before invoking this program.

 If you invoke this program as "editpolicy_offline" or "ccs-editpolicy_offline", you can edit policy files in /etc/ccs/ directory.

[AUTHORS]

 penguin-kernel _at_ I-love.SAKURA.ne.jp

 Line coloring feature is made by Yoshihiro Kusuno <yocto _at_ users.sourceforge.jp>.

EOF
fi
exit 0
