#! /bin/sh

if [ "$1" = "--version" ]
then
cat << EOF
tomoyo-pathmatch 2.2.0

Copyright (C) 2005-2009 NTT DATA CORPORATION.

This program is free software; you may redistribute it under the terms of
the GNU General Public License. This program has absolutely no warranty.
EOF
elif [ "$1" = "--help" ]
then
cat << EOF
Usage: tomoyo-pathmatch list_of_pathname_patterns

This program scans the filesystem for given pathname patterns.

You can use this program to determine how deep patterns are needed for defining 'file_pattern' or 'path_group'.

Examples:

# tomoyo-pathmatch '/etc/\*' '/tmp/\*'
 Search for pathnames matching '/etc/\*' or '/tmp/\*' pattern.

EOF
else
cat << EOF | help2man -i - -N -s 8 -n "Do TOMOYO Linux's pathname pattern matching on the filesystem" $0 | gzip -9 > man8/tomoyo-pathmatch.8.gz
[SEE ALSO]

 tomoyo-patternize (8)

[AUTHORS]

 penguin-kernel _at_ I-love.SAKURA.ne.jp

EOF
fi
exit 0
