#! /bin/sh
#
# Policy Loader.
#
# Copyright (C) 2005-2009  NTT DATA CORPORATION
#
# Version: 1.6.7 2009/04/01
#
# This program is executed automatically by kernel
# when execution of /sbin/init is requested.
#

PROFILE="default"
TOMOYO_NOLOAD=0
TOMOYO_QUIET=0
PROC_UNMOUNT=0
CHDIR_OK=0

# Mount /proc if not mounted.
if [ ! -d /proc/self/ ]; then
    mount -nt proc none /proc && PROC_UNMOUNT=1
fi

# Unmount /proc and exit if policy interface doesn't exist.
if [ ! -d /proc/ccs/ ]; then
    [ $PROC_UNMOUNT -eq 1 ] && umount -n /proc
    exit 1
fi

# Open /dev/console if stdio are not connected.
#
# WARNING: Don't let this program be invoked implicitly
# if you are not operating from console.
# Otherwise, you will get unable to respond to prompt
# if something went wrong.
if [ ! -r /proc/self/fd/0 ]; then
    exec 0< /dev/console
    exec 1> /dev/console
    exec 2> /dev/console
fi

# Check /proc/cmdline and /proc/self/cmdline
for i in `cat /proc/cmdline` "$@"
  do
  case $i in
      (CCS=ask)
      PROFILE="ask"
      ;;
      (CCS=default)
      PROFILE="default"
      ;;
      (CCS=disabled)
      PROFILE="disable"
      ;;
      (CCS=*)
      PROFILE=`echo $i | cut -b 5-`
      ;;
      (TOMOYO_NOLOAD)
      TOMOYO_NOLOAD=1
      ;;
      (TOMOYO_QUIET)
      TOMOYO_QUIET=1
      ;;
  esac
done

# Does policy directory exist?
if cd /etc/ccs/ 2> /dev/null; then
    CHDIR_OK=1
else
    PROFILE="disable"
fi

# Does selected profile exist?
if [ $CHDIR_OK -eq 1 ]; then
    if [ "x$PROFILE" = "xdefault" ]; then
	if [ ! -r profile.conf ]; then
	    echo "TOMOYO Linux: Default profile doesn't exist."
	    PROFILE="ask"
	fi
    elif [ "x$PROFILE" != "xask" -a "x$PROFILE" != "xdisable" ]; then
	if [ ! -r profile-$PROFILE.conf ]; then
	    echo "TOMOYO Linux: Specified profile doesn't exist."
	    PROFILE="ask"
	fi
    fi
fi

# Show prompt if something went wrong or explicitly asked.
if [ "x$PROFILE" = "xask" ]; then
    while :
      do
      echo "TOMOYO Linux: Select a profile from the following list."
      if [ $CHDIR_OK -eq 1 ]; then
	  # Show profiles in policy directory.
	  [ -r profile.conf ] && echo "default"
	  echo profile-*.conf | awk ' { gsub("profile-default.conf", ""); gsub("profile-disable.conf", ""); gsub("profile-", ""); gsub(".conf", ""); if ( $0 != "*") print $0; } '
      fi
      echo "disable"
      PROFILE=""
      read -p "> " PROFILE
      if [ $CHDIR_OK -eq 1 ]; then
	  [ -r profile.conf -a "x$PROFILE" = "xdefault" ] && break
	  [ "x$PROFILE" != "xdefault" -a "x$PROFILE" != "xdisable" -a -r profile-$PROFILE.conf ] && break
      fi
      [ "x$PROFILE" = "xdisable" ] && break
      [ "x$PROFILE" = "xTOMOYO_NOLOAD" ] && TOMOYO_NOLOAD=1
      [ "x$PROFILE" = "xTOMOYO_QUIET" ] && TOMOYO_QUIET=1
    done
fi

# Load policy.
if [ $CHDIR_OK -eq 1 ]; then
    [ -r manager.base ] && cat manager.base > /proc/ccs/manager
    [ -r manager.conf ] && cat manager.conf > /proc/ccs/manager
    [ -r system_policy.base -a -w /proc/ccs/system_policy ] && cat system_policy.base > /proc/ccs/system_policy
    [ -r system_policy.conf -a -w /proc/ccs/system_policy ] && cat system_policy.conf > /proc/ccs/system_policy
    [ -r exception_policy.base -a -w /proc/ccs/exception_policy ] && cat exception_policy.base > /proc/ccs/exception_policy
    [ -r exception_policy.conf -a -w /proc/ccs/exception_policy ] && cat exception_policy.conf > /proc/ccs/exception_policy
    [ $TOMOYO_NOLOAD -eq 0 -a -r domain_policy.base -a -w /proc/ccs/domain_policy ] && cat domain_policy.base > /proc/ccs/domain_policy
    [ $TOMOYO_NOLOAD -eq 0 -a -r domain_policy.conf -a -w /proc/ccs/domain_policy ] && cat domain_policy.conf > /proc/ccs/domain_policy
    [ -r profile.base ] && cat profile.base > /proc/ccs/profile
    if [ "x$PROFILE" = "xdefault" ]; then
	[ -r profile.conf ] && cat profile.conf > /proc/ccs/profile
    elif [ "x$PROFILE" != "xdisable" ]; then
	[ -r profile-$PROFILE.conf ] && cat profile-$PROFILE.conf > /proc/ccs/profile
    fi
    [ -r meminfo.base ] && cat meminfo.base > /proc/ccs/meminfo
    [ -r meminfo.conf ] && cat meminfo.conf > /proc/ccs/meminfo
fi

# Use disabled mode?
if [ "x$PROFILE" = "xdisable" ]; then
    for i in `seq 0 255`; do echo $i-COMMENT= ; done > /proc/ccs/profile
    grep -vF -- -COMMENT= /proc/ccs/profile | sed -e 's/[0-9]*$/0/' > /proc/ccs/profile
fi

# Disable verbose mode?
if [ $TOMOYO_QUIET -eq 1 ]; then
    grep -F TOMOYO_VERBOSE /proc/ccs/profile | sed -e 's/[0-9]*$/0/' > /proc/ccs/profile
fi

# Do additional initialization.
[ -x /etc/ccs/ccs-post-init ] && /etc/ccs/ccs-post-init

[ -r /proc/ccs/domain_policy ] && awk ' BEGIN { domain=0; acl=0; } { if ( $1 == "<kernel>" ) domain++; else if ( $1 != "" && $1 != "use_profile") acl++; } END { print domain " domains. " acl " ACL entries."; } ' /proc/ccs/domain_policy

# Show memory usage.
awk ' BEGIN { shared_mem=0; private_mem=0; } { if ( $1 == "Shared:" ) shared_mem = $2 / 1024; else if ( $1 == "Private:" ) private_mem = $2 / 1024; } END { print shared_mem " KB shared. " private_mem " KB private."; } ' /proc/ccs/meminfo

[ $PROC_UNMOUNT -eq 1 ] && umount -n /proc
exit 0
