#! /bin/sh

if [ "$1" = "--version" ]
then
cat << EOF
ccs-setlevel 1.5.5

Copyright (C) 2005-2008 NTT DATA CORPORATION.

This program is free software; you may redistribute it under the terms of
the GNU General Public License. This program has absolutely no warranty.
EOF
elif [ "$1" = "--help" ]
then
cat << EOF
Usage: ccs-setlevel profile_index-profile_name=profile_value ...

This program updates TOMOYO Linux's profile.

You can see list of profiles currently defined via /proc/ccs/profile .

Examples:

# ccs-setlevel 2-TOMOYO_VERBOSE=1
 Turn on verbose mode for profile 2.

# ccs-setlevel 3-ALLOW_ENFORCE_GRACE=1
 Turn on delayed enforcing mode for profile 3.

EOF
else
cat << EOF | help2man -i - -N -s 8 -n "Update TOMOYO Linux's profile" $0 | gzip -9 > man8/ccs-setlevel.8.gz
[SEE ALSO]

 ccs-loadpolicy (8)

[NOTES]

 This is a symbolic link to /usr/lib/ccs/setlevel .

 You need to register either path to this program ( /usr/lib/ccs/setlevel ) or a domain for this program in /proc/ccs/manager before invoking this program.

[AUTHORS]

 penguin-kernel _at_ I-love.SAKURA.ne.jp

EOF
fi
exit 0
