#! /bin/sh

if [ "$1" = "--version" ]
then
cat << EOF
realpath 1.5.2

Copyright (C) 2005-2007 NTT DATA CORPORATION.

This program is free software; you may redistribute it under the terms of
the GNU General Public License. This program has absolutely no warranty.
EOF
elif [ "$1" = "--help" ]
then
cat << EOF
Usage: realpath [-n] pathname

This program displays canonicalized pathname.

Examples:

# realpath /proc/self

EOF
else
cat << EOF | help2man -i - -N -s 1 -n "display canonical pathname" $0 | gzip -9 > man1/realpath.1.gz
[SEE ALSO]

 readlink (1)

[NOTES]

 This is equivalent to "readlink -f" if your system has the GNU core utilities package installed.
 This command is prepared for compatibility with systems that have "readlink" in other packages installed.

[AUTHORS]

 penguin-kernel _at_ I-love.SAKURA.ne.jp

EOF
fi
exit 0
