#! /bin/sh

if [ "$1" = "--version" ]
then
cat << EOF
pathmatch 1.5.1

Copyright (C) 2005-2007 NTT DATA CORPORATION.

This program is free software; you may redistribute it under the terms of
the GNU General Public License. This program has absolutely no warranty.
EOF
elif [ "$1" = "--help" ]
then
cat << EOF
Usage: pathmatch list_of_pathname_patterns

This program scans the filesystem for given pathname patterns.

You can use this program to determine how deep patterns are needed for defining 'file_pattern' or 'path_group'.

Examples:

# pathmatch '/etc/\*' '/tmp/\*'
 Search for pathnames matching '/etc/\*' or '/tmp/\*' pattern.

EOF
else
cat << EOF | help2man -i - -N -s 8 -n "Do TOMOYO Linux's pathname pattern matching on the filesystem" $0 | gzip -9 > /usr/share/man/man8/pathmatch.8.gz
[SEE ALSO]

 patternize (8)

[NOTES]

 You may create a symbolic link to this program named ccs-pathmatch if you wish.

[AUTHORS]

 penguin-kernel _at_ I-love.SAKURA.ne.jp

EOF
fi
exit 0
