#! /bin/sh

if [ "$1" = "--version" ]
then
cat << EOF
patternize 1.5.1

Copyright (C) 2005-2007 NTT DATA CORPORATION.

This program is free software; you may redistribute it under the terms of
the GNU General Public License. This program has absolutely no warranty.
EOF
elif [ "$1" = "--help" ]
then
cat << EOF
Usage: patternize pattern [pattern ...] < list_of_pathnames > new_list_of_pathnames

This program reads domain policy from standard input and replaces pathnames with patterns if the pathname matches to patterns given at commandline and writes to standard output.

Pathnames that contains execute permission and domainnames won't be patterned.

Examples:

# patternize '/tmp/php\?\?\?\?\?\?' < /etc/ccs/domain_policy.conf > /etc/ccs/domain_policy2.conf
 Replace pathnames that matches to /tmp/php\?\?\?\?\?\? pattern.

EOF
else
cat << EOF | help2man -i - -N -s 8 -n "Convert TOMOYO Linux's pathnames into patterns" $0 | gzip -9 > /usr/share/man/man8/patternize.8.gz
[SEE ALSO]

 findtemp (8)

[NOTES]

 You may create a symbolic link to this program named ccs-patternize if you wish.

[AUTHORS]

 penguin-kernel _at_ I-love.SAKURA.ne.jp

EOF
fi
exit 0
