#! /bin/sh
#
# fgrep for /sys/kernel/security/tomoyo/domain_policy .
#
# Copyright (C) 2005-2009  NTT DATA CORPORATION
#
# Version: 2.2.0   2009/05/28
#
# Usage: tomoyo-domainmatch string_to_find
#
# Example: tomoyo-domainmatch /etc/fstab
#
exec awk -v STR="$1" -- ' BEGIN { flag = 0; } { if ( $1 == "<kernel>" ) { domain = $0; flag = 0; } else if (index($0, STR) > 0) { if (flag == 0) { print ""; print domain; } flag = 1; print $0; } } ' /sys/kernel/security/tomoyo/domain_policy
