#! /bin/sh

if [ "$1" = "--version" ]
then
cat << EOF
ccs-loadpolicy 1.6.7-rc

Copyright (C) 2005-2009 NTT DATA CORPORATION.

This program is free software; you may redistribute it under the terms of
the GNU General Public License. This program has absolutely no warranty.
EOF
elif [ "$1" = "--help" ]
then
cat << EOF
Usage: ccs-loadpolicy [-][s][e][d][a][f][p][m][u]

This program loads TOMOYO Linux's policy from files or standard input into kernel.

 -     Read policy from stdin. Specify only one of "sedpmu" option when you use this option.

 s     Load system policy. ( /etc/ccs/system_policy.base + /etc/ccs/system_policy.conf => /proc/ccs/system_policy )

 e     Load exception policy. ( /etc/ccs/exception_policy.base + /etc/ccs/exception_policy.conf => /proc/ccs/exception_policy )

 d     Load domain policy. ( /etc/ccs/domain_policy.base + /etc/ccs/domain_policy.conf => /proc/ccs/domain_policy )

 a     Load system policy, exception policy and domain policy.

 p     Load profile. ( /etc/ccs/profile.base + /etc/ccs/profile.conf => /proc/ccs/profile )

 m     Load manager. ( /etc/ccs/manager.base + /etc/ccs/manager.conf => /proc/ccs/manager )

 u     Load meminfo. ( /etc/ccs/meminfo.base + /etc/ccs/meminfo.conf => /proc/ccs/meminfo )

 f     Erase on-memory policy before loading on-disk policy. If not specified, on-disk policy is appended to on-memory policy.
       This option is valid for "seda" options.

Examples:

# echo "allow_read /proc/meminfo" | ccs-loadpolicy -e
 Add "allow_read /proc/meminfo" to exception policy.

# echo "delete allow_read /proc/meminfo" | ccs-loadpolicy -e
 Remove "allow_read /proc/meminfo" from exception policy.

# ( echo "<kernel>"; echo "allow_execute /sbin/init" ) | ccs-loadpolicy -d
 Add "allow_execute /sbin/init" to "<kernel>" domain.

# ccs-loadpolicy df
 Replace currently loaded domain policy with /etc/ccs/domain_policy.base + /etc/ccs/domain_policy.conf .

# ccs-loadpolicy d
 Append /etc/ccs/domain_policy.base + /etc/ccs/domain_policy.conf into currently loaded domain policy.

EOF
else
cat << EOF | help2man -i - -N -s 8 -n "Load TOMOYO Linux's policy manually" $0 | gzip -9 > man8/ccs-loadpolicy.8.gz
[SEE ALSO]

 ccs-init (8)

[NOTES]

 This is a symbolic link to /usr/lib/ccs/loadpolicy .

 You need to register either path to this program ( /usr/lib/ccs/loadpolicy ) or a domain for this program in /proc/ccs/manager before invoking this program.

[AUTHORS]

 penguin-kernel _at_ I-love.SAKURA.ne.jp

EOF
fi
exit 0
