#! /bin/sh

if [ "$1" = "--version" ]
then
cat << EOF
tomoyo-init 2.2.0

Copyright (C) 2005-2011 NTT DATA CORPORATION.

This program is free software; you may redistribute it under the terms of
the GNU General Public License. This program has absolutely no warranty.
EOF
elif [ "$1" = "--help" ]
then
cat << EOF
Usage: tomoyo-init

This program is automatically called to load policy from files into kernel when /sbin/init starts.

This program copies the following files.

   /etc/tomoyo/exception_policy.base + /etc/tomoyo/exception_policy.conf => /sys/kernel/security/tomoyo/exception_policy

   /etc/tomoyo/domain_policy.base + /etc/tomoyo/domain_policy.conf => /sys/kernel/security/tomoyo/domain_policy

   /etc/tomoyo/profile.base + /etc/tomoyo/profile.conf => /sys/kernel/security/tomoyo/profile

   /etc/tomoyo/manager.base + /etc/tomoyo/manager.conf => /sys/kernel/security/tomoyo/manager

Examples:

None.

EOF
else
cat << EOF | help2man -i - -N -s 8 -n "Load TOMOYO Linux's policy automatically" $0 | gzip -9 > man8/tomoyo-init.8.gz
[SEE ALSO]

 ccs-loadpolicy (8)

[NOTES]

 If something went wrong, a prompt is shown so that the administrator can take action before the kernel gets panic.

 You don't need to invoke this program manually.

 To load policy after /sbin/init starts, use ccs-loadpolicy instead.

[AUTHORS]

 penguin-kernel _at_ I-love.SAKURA.ne.jp

EOF
fi
exit 0
