#! /bin/sh

if [ "$1" = "--version" ]
then
cat << EOF
ccs-notifyd 1.8.0

Copyright (C) 2005-2010 NTT DATA CORPORATION.

This program is free software; you may redistribute it under the terms of
the GNU General Public License. This program has absolutely no warranty.
EOF
elif [ "$1" = "--help" ]
then
cat << EOF
Usage: ccs-notifyd

This program detects policy violation in enforcing mode and notify users (e.g. send a mail). You can know the occurence of policy violation in enforcing mode as soon as possible. You may use this program for holding your judgement of the request that violates policy in enforcing mode provided that you can login to the system and start "ccs-queryd" command for responding.

See /etc/ccs/tools/notifyd.conf for configuration.

EOF
else
cat << EOF | help2man -i - -N -s 8 -n "Notify TOMOYO Linux's policy violation" $0 | gzip -9 > man8/ccs-notifyd.8.gz
[SEE ALSO]

 ccs-queryd (8)

[NOTES]

 You need to register either path to this program ( /usr/sbin/ccs-notifyd ) or a domain for this program in /proc/ccs/manager before invoking this program if you want to use holding your judgement.

[AUTHORS]

 penguin-kernel _at_ I-love.SAKURA.ne.jp

EOF
fi
exit 0
