#! /bin/sh

if [ "$1" = "--version" ]
then
cat << EOF
ccs-checkpolicy 1.6.9

Copyright (C) 2005-2011 NTT DATA CORPORATION.

This program is free software; you may redistribute it under the terms of
the GNU General Public License. This program has absolutely no warranty.
EOF
elif [ "$1" = "--help" ]
then
cat << EOF
Usage: ccs-checkpolicy {s|e|d} < policy_to_check

This program validates TOMOYO Linux's policy.

 s     Interpret input as system policy. ( /etc/ccs/system_policy.conf )

 e     Interpret input as exception policy. ( /etc/ccs/exception_policy.conf )

 d     Interpret input as domain policy. ( /etc/ccs/domain_policy.conf )

Examples:

# ccs-checkpolicy e < /etc/ccs/exception_policy.conf
 Check for errors in exception policy.

# ccs-checkpolicy d < /etc/ccs/domain_policy.conf
 Check for errors in domain policy.

EOF
else
cat << EOF | help2man -i - -N -s 8 -n "TOMOYO Linux's policy validator" $0 | gzip -9 > man8/ccs-checkpolicy.8.gz
[NOTES]
 
 This is a symbolic link to /usr/lib/ccs/checkpolicy .

[AUTHORS]

 penguin-kernel _at_ I-love.SAKURA.ne.jp

EOF
fi
exit 0
