#! /bin/sh
#
# fgrep for domain /proc/ccs/domain_policy .
#
# Copyright (C) 2005-2011  NTT DATA CORPORATION
#
# Version: 1.6.9   2011/04/01
#
# Usage: domainmatch string_to_find
#
# Example: domainmatch /etc/fstab
#

POLICY_FILE="/proc/ccs/domain_policy"
[ -r /sys/kernel/security/tomoyo/domain_policy ] && POLICY_FILE="/sys/kernel/security/tomoyo/domain_policy"

awk -v STR="$1" -- ' BEGIN { flag = 0; } { if ( $1 == "<kernel>" ) { domain = $0; flag = 0; } else if (index($0, STR) > 0) { if (flag == 0) { print ""; print domain; } flag = 1; print $0; } } ' $POLICY_FILE 

#awk -v STR="$1" -- ' { if ( $1 == "<kernel>" ) domain = $0; else if (index($0, STR) > 0) { print domain; print $0; } } ' $POLICY_FILE
