#! /bin/sh

if [ "$1" = "--version" ]
then
cat << EOF
ccs-diffpolicy 1.7.3

Copyright (C) 2005-2011 NTT DATA CORPORATION.

This program is free software; you may redistribute it under the terms of
the GNU General Public License. This program has absolutely no warranty.
EOF
elif [ "$1" = "--help" ]
then
cat << EOF
Usage: ccs-diffpolicy old_domain_policy new_domain_policy

Examples:

# ccs-diffpolicy /etc/ccs/domain_policy.old /etc/ccs/domain_policy.new
 Make policy diff for domain policy .

# ccs-diffpolicy - /proc/ccs/domain_policy
 Make policy diff for domain policy . Use stdin for old_domain_policy.

# ccs-diffpolicy /proc/ccs/domain_policy -
 Make policy diff for domain policy . Use stdin for new_domain_policy.

EOF
else
cat << EOF | help2man -i - -N -s 8 -n "Diff TOMOYO Linux's domain policy" $0 | gzip -9 > man8/ccs-diffpolicy.8.gz
[SEE ALSO]

 ccs-loadpolicy (8)
 ccs-patternize (8)

[AUTHORS]

 penguin-kernel _at_ I-love.SAKURA.ne.jp

EOF
fi
exit 0
