#! /bin/sh

if [ "$1" = "--version" ]
then
cat << EOF
tomoyo-findtemp 2.3.0

Copyright (C) 2005-2011 NTT DATA CORPORATION.

This program is free software; you may redistribute it under the terms of
the GNU General Public License. This program has absolutely no warranty.
EOF
elif [ "$1" = "--help" ]
then
cat << EOF
Usage: tomoyo-findtemp < list_of_pathnames

This program reads list of pathnames from standard input and checks the existence of pathnames, and dumps the nonexistent pathnames.

The nonexistent pathnames are likely used as temporary pathnames. So find the naming rules from similar nonexistent pathnames and append the pattern to /etc/tomoyo/exception_policy.conf and /sys/kernel/security/tomoyo/exception_policy .

You can pass the content of /etc/tomoyo/domain_policy.conf or /sys/kernel/security/tomoyo/domain_policy using redirection or pipes to the standard input of this program.

Examples:

# tomoyo-findtemp < /sys/kernel/security/tomoyo/domain_policy
 Search for nonexistent pathnames from domain policy.

EOF
else
cat << EOF | help2man -i - -N -s 8 -n "Detect TOMOYO Linux's temporary pathnames" $0 | gzip -9 > man8/tomoyo-findtemp.8.gz
[SEE ALSO]

 tomoyo-patternize (8)

[AUTHORS]

 penguin-kernel _at_ I-love.SAKURA.ne.jp

EOF
fi
exit 0
