#! /bin/sh

if [ "$1" = "--version" ]
then
cat << EOF
ccs-ld-watch 1.7.3

Copyright (C) 2005-2011 NTT DATA CORPORATION.

This program is free software; you may redistribute it under the terms of
the GNU General Public License. This program has absolutely no warranty.
EOF
elif [ "$1" = "--help" ]
then
cat << EOF
Usage: ccs-ld-watch

Appends shared libraries to exception policy automatically using "allow_read" directive when the location of shared libraries in /etc/ld.so.cache has changed.

By running this program while updating packages, you can avoid errors "unable to start applications because shared libraries are unreadable" when the pathnames of shared libraries accessed by general programs has changed.

Examples:

# ccs-ld-watch

EOF
else
cat << EOF | help2man -i - -N -s 8 -n "Update TOMOYO Linux's library's pathnames automatically" $0 | gzip -9 > man8/ccs-ld-watch.8.gz
[SEE ALSO]

 ccs-queryd (8)

[NOTES]

 You need to register either path to this program ( /usr/sbin/ccs-ld-watch ) or a domain for this program in /proc/ccs/manager before invoking this program.

 This program is obsolete. You can run ccs-queryd instead of running this program.

[AUTHORS]

 penguin-kernel _at_ I-love.SAKURA.ne.jp

EOF
fi
exit 0
