#! /bin/sh

if [ "$1" = "--version" ]
then
cat << EOF
tomoyo-setlevel 2.3.0

Copyright (C) 2005-2011 NTT DATA CORPORATION.

This program is free software; you may redistribute it under the terms of
the GNU General Public License. This program has absolutely no warranty.
EOF
elif [ "$1" = "--help" ]
then
cat << EOF
Usage: tomoyo-setlevel name=value ...

This program updates TOMOYO Linux's profile.

You can see list of profiles currently defined via /sys/kernel/security/tomoyo/profile .

Examples:

# tomoyo-setlevel "PREFERENCE::enforcing={ verbose=yes }"
 Turn on verbose mode for enforcing mode.

EOF
else
cat << EOF | help2man -i - -N -s 8 -n "Update TOMOYO Linux's profile" $0 | gzip -9 > man8/tomoyo-setlevel.8.gz
[SEE ALSO]

 tomoyo-loadpolicy (8)

[NOTES]

 You need to register either path to this program ( /usr/sbin/tomoyo-setlevel ) or a domain for this program in /sys/kernel/security/tomoyo/manager before invoking this program.

[AUTHORS]

 penguin-kernel _at_ I-love.SAKURA.ne.jp

EOF
fi
exit 0
