#! /bin/sh

if [ "$1" = "--version" ]
then
cat << EOF
tomoyo-patternize 2.3.0

Copyright (C) 2005-2011 NTT DATA CORPORATION.

This program is free software; you may redistribute it under the terms of
the GNU General Public License. This program has absolutely no warranty.
EOF
elif [ "$1" = "--help" ]
then
cat << EOF
Usage: tomoyo-patternize pattern [pattern ...] < old_domain_policy > new_domain_policy

This program reads domain policy from standard input and replaces pathnames with patterns if the pathname matches to patterns given at commandline and writes to standard output.

Pathnames for execute permission and domainnames won't be replaced.

Examples:

# tomoyo-patternize '/tmp/php\?\?\?\?\?\?' < /etc/tomoyo/domain_policy.conf > /etc/tomoyo/domain_policy2.conf
 Replace pathnames that match /tmp/php\?\?\?\?\?\? pattern with /tmp/php\?\?\?\?\?\? .

# tomoyo-patternize 'file_pattern /tmp/php\?\?\?\?\?\?' < /etc/tomoyo/domain_policy.conf > /etc/tomoyo/domain_policy2.conf
 Replace pathnames that match /tmp/php\?\?\?\?\?\? pattern with /tmp/php\?\?\?\?\?\? .

# tomoyo-patternize 'path_group GROUP1 /tmp/php\?\?\?\?\?\?' < /etc/tomoyo/domain_policy.conf > /etc/tomoyo/domain_policy2.conf
 Replace pathnames that match /tmp/php\?\?\?\?\?\? pattern with @GROUP1.

# tomoyo-patternize 'number_group GROUP2 0-100' 'number_group GROUP2 100-200'< /etc/tomoyo/domain_policy.conf > /etc/tomoyo/domain_policy2.conf
 Replace integers between 0-100 or 100-200 with @GROUP2 .

# tomoyo-patternize 'address_group LOCALHOST 127.0.0.1' 'address_group LOCALHOST 0:0:0:0:0:0:0:1' < /etc/tomoyo/domain_policy.conf > /etc/tomoyo/domain_policy2.conf
 Replace ip addresses 127.0.0.1 or 0:0:0:0:0:0:0:1 with @LOCALHOST.

EOF
else
cat << EOF | help2man -i - -N -s 8 -n "Convert TOMOYO Linux's pathnames into patterns" $0 | gzip -9 > man8/tomoyo-patternize.8.gz
[SEE ALSO]

 tomoyo-findtemp (8)
 tomoyo-diffpolicy(8)

[AUTHORS]

 penguin-kernel _at_ I-love.SAKURA.ne.jp

EOF
fi
exit 0
