#! /bin/sh

if [ "$1" = "--version" ]
then
cat << EOF
domainmatch 1.5.1

Copyright (C) 2005-2007 NTT DATA CORPORATION.

This program is free software; you may redistribute it under the terms of
the GNU General Public License. This program has absolutely no warranty.
EOF
elif [ "$1" = "--help" ]
then
cat << EOF
Usage: domainmatch pathname

This program scans domain policy for given pathname.

Examples:

# domainmatch /etc/fstab
 Search for domains that accesses /etc/fstab .

EOF
else
cat << EOF | help2man -i - -N -s 8 -n "Scan TOMOYO Linux's domain policy" $0 | gzip -9 > /usr/share/man/man8/domainmatch.8.gz
[SEE ALSO]

 findtemp (8)

[NOTES]

 You may create a symbolic link to this program named ccs-domainmatch if you wish.

[AUTHORS]

 penguin-kernel _at_ I-love.SAKURA.ne.jp

EOF
fi
exit 0
