#! /bin/sh

if [ "$1" = "--version" ]
then
cat << EOF
tomoyo-diffpolicy 2.3.0

Copyright (C) 2005-2011 NTT DATA CORPORATION.

This program is free software; you may redistribute it under the terms of
the GNU General Public License. This program has absolutely no warranty.
EOF
elif [ "$1" = "--help" ]
then
cat << EOF
Usage: tomoyo-diffpolicy old_domain_policy new_domain_policy

Examples:

# tomoyo-diffpolicy /etc/tomoyo/domain_policy.old /etc/tomoyo/domain_policy.new
 Make policy diff for domain policy .

# tomoyo-diffpolicy - /sys/kernel/security/tomoyo/domain_policy
 Make policy diff for domain policy . Use stdin for old_domain_policy.

# tomoyo-diffpolicy /sys/kernel/security/tomoyo/domain_policy -
 Make policy diff for domain policy . Use stdin for new_domain_policy.

EOF
else
cat << EOF | help2man -i - -N -s 8 -n "Diff TOMOYO Linux's domain policy" $0 | gzip -9 > man8/tomoyo-diffpolicy.8.gz
[SEE ALSO]

 tomoyo-loadpolicy (8)
 tomoyo-patternize (8)

[AUTHORS]

 penguin-kernel _at_ I-love.SAKURA.ne.jp

EOF
fi
exit 0
