#! /bin/sh

if [ "$1" = "--version" ]
then
cat << EOF
tomoyo-queryd 2.3.0

Copyright (C) 2005-2011 NTT DATA CORPORATION.

This program is free software; you may redistribute it under the terms of
the GNU General Public License. This program has absolutely no warranty.
EOF
elif [ "$1" = "--help" ]
then
cat << EOF
Usage: tomoyo-queryd [--no-update|--ask-update|remote_ip:remote_port]

This program detects policy violation in enforcing mode and displays the access request. You can tell the system whether the access request should be granted (or granted and policy should be appended to grant the access request) or rejected after you validate the access request.

By running this program while updating packages, you can avoid errors due to insufficient permissions.

Never grant access requests unconditionally. The cause of policy violation is not always updating packages, but may by malicious requests by attackers. If you grant access requests caused by malicious requests by attackers, the system gets intruded.

If you don't give --no-update option, this program also detects pathname changes of globally readable files.
If you give --ask-update option, this program asks you whether or not to append created pathnames which are registered in /etc/ld.so.cache to globally readable files, and asks you whether or not to remove deleted pathnames from globally readable files.
If you omit options, this program automatically appends created pathnames which are registered in /etc/ld.so.cache to globally readable files, and automatically removes deleted pathnames from globally readable files.

By running this program without --no-update option, you can avoid errors like "unable to start applications because shared libraries are unreadable" when the pathnames of shared libraries accessed by general programs has changed.

 remote_ip:remote_port     Receive policy from agent listening at specified IP address and port number. 

Examples:

# tomoyo-queryd
 Handle local query.

# tomoyo-queryd 192.168.1.1:10000
 Handle remote query via agent listening at 192.168.1.1:10000 .

Usage is available at http://tomoyo.sourceforge.jp/2.3/enforcing.html

EOF
else
cat << EOF | help2man -i - -N -s 8 -n "Handle TOMOYO Linux's delayed enforcing mode" $0 | gzip -9 > man8/tomoyo-queryd.8.gz
[NOTES]

 You need to register either path to this program ( /usr/sbin/tomoyo-queryd ) or a domain for this program in /sys/kernel/security/tomoyo/manager before invoking this program.

[SEE ALSO]

 tomoyo-editpolicy-agent (8)

[AUTHORS]

 penguin-kernel _at_ I-love.SAKURA.ne.jp

EOF
fi
exit 0
