=head1 NAME

ccs-loadpolicy - load TOMOYO Linux manually

=head1 SYNOPSIS

B<ccs-loadpolicy> [I<option>]

B<ccs-loadpolicy> [I<option>] [I<remote_ip:remote_port>]

=head1 DESCRIPTION

This program reads TOMOYO Linux policy from standard input and loads it into the kernel.

=head1 OPTIONS

=over 4

=item B<-e>

Append to F</proc/ccs/exception_policy>.

=item B<-ef>

Overwrite F</proc/ccs/exception_policy>.

=item B<-d>

Append to F</proc/ccs/domain_policy>.

=item B<-df>

Overwrite F</proc/ccs/domain_policy>.

=item B<-m>

Append to F</proc/ccs/manager>.

=item B<-p>

Append to F</proc/ccs/profile>.

=item B<-s>

Append to F</proc/ccs/stat>.

=item I<remote_ip:remote_port>

Write to policy on a remote system via an agent waiting at port I<remote_port> on IP address I<remote_ip>.

=back

=head1 EXAMPLES

=over 4

=item B<Append a line to exception policy>

  echo "acl_group 0 file read proc:/meminfo" | ccs-loadpolicy -e

=item B<Remove a line from exception policy>

  echo "delete acl_group 0 file read proc:/meminfo" | ccs-loadpolicy -e

=item B<Append a line to domain policy>

  ( echo "<kernel>"; echo "file execute /sbin/init" ) | ccs-loadpolicy -d

=item B<Replace currently loaded domain policy>

  ccs-loadpolicy -df < /etc/ccs/domain_policy.conf

=item B<Append to policy remotely>

  ccs-loadpolicy -d 192.168.1.1:10000 < /etc/ccs/192.168.1.1/domain_policy.conf

=item B<Remove a line from C</proc/ccs/manager>>

  echo "delete /usr/sbin/ccs-queryd" | ccs-loadpolicy -m

=back

=head1 BUGS

If you find any bugs, send an email to E<lt>tomoyo-users-en@lists.osdn.meE<gt>.

=head1 AUTHORS

=over 4

=item Tetsuo Handa E<lt>penguin-kernel@I-love.SAKURA.ne.jpE<gt>

Main author.

=item Jamie Nguyen E<lt>jamie@tomoyolinux.co.ukE<gt>

Documentation and website.

=back

=head1 SEE ALSO

B<ccs-savepolicy>(8), B<ccs-editpolicy>(8), B<ccs-editpolicy-agent>(8), B<ccs-init>(8)

See E<lt>https://tomoyo.osdn.jpE<gt> for more information.
