#!/bin/bash

if tput setaf 0 &>/dev/null; then
	ALL_OFF="$(tput sgr0)"
	BOLD="$(tput bold)"
	GREEN="${BOLD}$(tput setaf 2)"
	RED="${BOLD}$(tput setaf 1)"
else
	ALL_OFF="\e[1;0m"
	BOLD="\e[1;1m"
	GREEN="${BOLD}\e[1;32m"
	RED="${BOLD}\e[1;31m"
fi

msg() {
   	printf '%s\n' "${GREEN}==>${ALL_OFF}${BOLD} ${@}${ALL_OFF}" >&2
}
error() {
    printf '%s\n' "${RED}==>${ALL_OFF}${BOLD} ${@}${ALL_OFF}" >&2
	exit 1
}

setup_rpmbuild_tree() {
	msg "Setting up a clean rpmbuild tree ..."
	rm -rf "${RPM_BUILD_DIR}"
	rpmdev-setuptree || error "ERROR: rpmbuild tree setup failed"
	rm -rf "${RPM_BUILD_DIR}/SOURCES" \
		&& ln -sf "${RPM_SOURCE_DIR}" "${RPM_BUILD_DIR}/SOURCES"
}
setup_source_dir() {
	msg "Setting up source directory ..."
	if [[ ! -d "${1}" ]]; then
		mkdir "${1}" || error "ERROR: directory creation failed"
	fi
	rm -rf "${RPM_BUILD_DIR}/SOURCES"
	ln -sf "${1}" "${RPM_BUILD_DIR}/SOURCES" || error "ERROR: symlink creation failed"
}	
download_file() {
	if [[ ! -f "${2}" ]]; then
		msg "Downloading ${1} ..."
		wget "${1}" -O "${2}" || error "ERROR: file download failed"
	fi
}
verify_signature() {
	msg "Verifying signature for ${1} ..."
	rpm --checksig "${1}" || error "ERROR: signature verification failed"
}
install_srpm() {
	msg "Installing ${1} SRPM ..."
	rpm -ivh "${1}" || error "ERROR: ${1} SRPM installation failed"
}
