=head1 NAME

tomoyo-sortpolicy - domain policy sorting utility for TOMOYO Linux

=head1 SYNOPSIS

B<tomoyo-sortpolicy>

=head1 DESCRIPTION

This program reads domain policy from standard input and send the sorted contents to standard output. This is similar to B<sort>(1), except that sorting is done per domain.

=head1 EXAMPLES

=over 4

=item B<Sort domain policy>

  tomoyo-savepolicy -d | tomoyo-sortpolicy

=back

=head1 BUGS

If you find any bugs, send an email to E<lt>tomoyo-users-en@lists.osdn.meE<gt>.

=head1 AUTHORS

=over 4

=item Tetsuo Handa E<lt>penguin-kernel@I-love.SAKURA.ne.jpE<gt>

Main author.

=item Jamie Nguyen E<lt>jamie@tomoyolinux.co.ukE<gt>

Documentation and website.

=back

=head1 SEE ALSO

B<sort>(1)

See E<lt>https://tomoyo.osdn.jpE<gt> for more information.
