=head1 NAME

tomoyo-init - load TOMOYO Linux policy automatically

=head1 SYNOPSIS

B<tomoyo-init>

=head1 DESCRIPTION

When F</sbin/init> starts, the kernel automatically calls this program. Policy files that have been saved to disk are subsequently loaded into kernel memory.

This program copies the following files:

  /etc/tomoyo/exception_policy.base + /etc/tomoyo/exception_policy.conf => /sys/kernel/security/tomoyo/exception_policy

  /etc/tomoyo/domain_policy.base + /etc/tomoyo/domain_policy.conf => /sys/kernel/security/tomoyo/domain_policy

  /etc/tomoyo/profile.base + /etc/tomoyo/profile.conf => /sys/kernel/security/tomoyo/profile

  /etc/tomoyo/manager.base + /etc/tomoyo/manager.conf => /sys/kernel/security/tomoyo/manager

You will not usually need to invoke this program manually.

=head1 BUGS

If you find any bugs, send an email to E<lt>tomoyo-users-en@lists.osdn.meE<gt>.

=head1 AUTHORS

=over 4

=item Tetsuo Handa E<lt>penguin-kernel@I-love.SAKURA.ne.jpE<gt>

Main author.

=item Jamie Nguyen E<lt>jamie@tomoyolinux.co.ukE<gt>

Documentation and website.

=back

=head1 SEE ALSO

B<tomoyo-loadpolicy>(8)

See E<lt>https://tomoyo.osdn.jpE<gt> for more information.
