#! /bin/sh
#
# fgrep for domain /proc/ccs/domain_policy .
#
# Copyright (C) 2005-2011  NTT DATA CORPORATION
#
# Version: 1.7.3   2011/04/01
#
# Usage: ccs-domainmatch string_to_find
#
# Example: ccs-domainmatch /etc/fstab
#

awk -v STR="$1" -- ' BEGIN { flag = 0; } { if ( $1 == "<kernel>" ) { domain = $0; flag = 0; } else if (index($0, STR) > 0) { if (flag == 0) { print ""; print domain; } flag = 1; print $0; } } ' /proc/ccs/domain_policy 

#awk -v STR="$1" -- ' { if ( $1 == "<kernel>" ) domain = $0; else if (index($0, STR) > 0) { print domain; print $0; } } ' /proc/ccs/domain_policy
